### ISSUE TITLE
Contao 4.4 ^

### ISSUE THREAD

**Issue by hermannbrauer** [richardhj/contao-notification_center_clockworksms#1]
is an adaptation to contao 4.4 and higher planned

**Comment by richardhj** [comment]
Can be installed now

**Comment by hermannbrauer** [comment]
Hey, can you please check again why your plugin is incompatible thanks

Contao 4.4.8 mit PHP 7.2

**Comment by richardhj** [comment]
Do you have the output of the composer task?

**Comment by hermannbrauer** [comment]
had tried the installation on the manager ... there is the bundle incompatible in composer works the installation!

**Comment by richardhj** [comment]
Hm, yeah…
I planned to do a Contao 4.4 release, incl. Contao Manager Plugin, in Spring'18.

**Comment by hermannbrauer** [comment]
Manual installation via Composer destroys the existing installation -- I want to wait until spring

**Comment by richardhj** [comment]
Ok, if this is the case I will take a closer look in the near future and will release a compatibility fix so that you can use the extension with Contao 4.

**Comment by richardhj** [comment]
I guess, this (1496feb9ab06f1afede42514cb30bd3f7409d616) did the trick. Please test.
